### ISSUE TITLE
질문을 주셨는데요. 잘하셨는데요?

### ISSUE THREAD

**Issue by niceaji** [junssource/start-fe#2]
https://github.com/junssource/start-fe/blob/350b56db72fa6e7ad24422113f836ce889ca319d/04/quiz2.html#L48

```
자바스크립트에서 객체.style.width 등으로 크기를 조절할 수 있을 것 같은데
브라우저로 보면 개발자도구 element에서도 크기가 표시되지만
화면 상에는 적용이 되지 않는 부분을 잘 모르겠습니다.

```
  화면상에 적용이 안된다는 표현을 잘 모르겠네요

**Comment by junssource** [comment]
감사합니다! 5주차 강의를 보고 알았는데, span 태그가 block이 아니라서
적용이 안 되었던 것 같습니다.
그래서 화면에 크기가 안 적용된 것 같아요.
